"use strict";

const fs = require("fs");
const path = require("path");

const workspace = process.env.GITHUB_WORKSPACE || process.cwd();

const SOURCE_REPO = process.env.SOURCE_REPO;
const SOURCE_BRANCH = process.env.SOURCE_BRANCH;
const SOURCE_DIR = process.env.SOURCE_DIR;
const TARGET_FILE = process.env.TARGET_FILE;

for (const [key, value] of Object.entries({
  SOURCE_REPO,
  SOURCE_BRANCH,
  SOURCE_DIR,
  TARGET_FILE,
})) {
  if (!value) {
    console.error(`Missing required environment variable: ${key}`);
    process.exit(1);
  }
}

const sourceDirPath = path.resolve(workspace, SOURCE_DIR);
const targetFilePath = path.resolve(workspace, TARGET_FILE);

// sourceUrl base for entries generated by this action
const sourceUrlBase = `https://raw.githubusercontent.com/${SOURCE_REPO}/refs/heads/${SOURCE_BRANCH}/${SOURCE_DIR}`;

// ---------------------------------------------------------------------------
// Read source .ttl files
// ---------------------------------------------------------------------------

const currentNames = [
  fs
    .readdirSync(sourceDirPath)
    .filter((f) => f.endsWith(".ttl"))
    .map((f) => path.basename(f, ".ttl"))
    .sort()[0],
];

const dataset = JSON.parse(fs.readFileSync(targetFilePath, "utf8"));

const ownsEntry = (entry) => entry.sourceUrl.includes(`/${SOURCE_REPO}/`);

const ownedEntries = dataset.conceptSchemes.filter(ownsEntry);
const otherEntries = dataset.conceptSchemes.filter((e) => !ownsEntry(e));

const ownedByRef = Object.fromEntries(ownedEntries.map((e) => [e.urlRef, e]));

const currentSet = new Set(currentNames);
const ownedSet = new Set(Object.keys(ownedByRef));

const toAdd = currentNames.filter((n) => !ownedSet.has(n));
const toRemove = [...ownedSet].filter((n) => !currentSet.has(n)).sort();

if (toAdd.length === 0 && toRemove.length === 0) {
  console.log("No changes needed.");
  process.exit(0);
}

for (const name of toRemove) console.log(`Removing: ${name}`);
for (const name of toAdd) console.log(`Adding:   ${name}`);

const updatedOwned = currentNames.map(
  (name) =>
    ownedByRef[name] ?? {
      urlRef: name,
      sourceUrl: `${sourceUrlBase}/${name}.ttl`,
    },
);

dataset.conceptSchemes = [...otherEntries, ...updatedOwned].sort((a, b) =>
  a.urlRef < b.urlRef ? -1 : a.urlRef > b.urlRef ? 1 : 0,
);

fs.writeFileSync(
  targetFilePath,
  JSON.stringify(dataset, null, 2) + "\n",
  "utf8",
);

console.log(`Done. +${toAdd.length} added, -${toRemove.length} removed.`);
