"use strict";

const path = require("path");
const {
  getCurrentNames,
  computeDiff,
  applyDiff,
  generateAllTtlContent,
  writeDataset,
  writeAllTtlAndZip,
} = require("./sync-lib");

const workspace = process.env.GITHUB_WORKSPACE || process.cwd();

const SOURCE_REPO = process.env.SOURCE_REPO;
const SOURCE_BRANCH = process.env.SOURCE_BRANCH;
const SOURCE_DIR = process.env.SOURCE_DIR;
const TARGET_FILE = process.env.TARGET_FILE;
const ALL_TTL_DIR = process.env.ALL_TTL_DIR;

for (const [key, value] of Object.entries({
  SOURCE_REPO,
  SOURCE_BRANCH,
  SOURCE_DIR,
  TARGET_FILE,
})) {
  if (!value) {
    console.error(`Missing required environment variable: ${key}`);
    process.exit(1);
  }
}

const sourceDirPath = path.resolve(workspace, SOURCE_DIR);
const targetFilePath = path.resolve(workspace, TARGET_FILE);

// sourceUrl base for entries generated by this action
const sourceUrlBase = `https://raw.githubusercontent.com/${SOURCE_REPO}/refs/heads/${SOURCE_BRANCH}/${SOURCE_DIR}`;

// ---------------------------------------------------------------------------
// Read source .ttl files
// ---------------------------------------------------------------------------

const currentNames = getCurrentNames(sourceDirPath);
const dataset = JSON.parse(require("fs").readFileSync(targetFilePath, "utf8"));

// ---------------------------------------------------------------------------
// Sync dataset.json
// ---------------------------------------------------------------------------

const diff = computeDiff(currentNames, dataset, SOURCE_REPO);
const updatedDataset = applyDiff(dataset, diff, sourceUrlBase);

if (updatedDataset) {
  for (const name of diff.toRemove) console.log(`Removing: ${name}`);
  for (const name of diff.toAdd) console.log(`Adding:   ${name}`);

  writeDataset(targetFilePath, updatedDataset);
  console.log(`Dataset.json: +${diff.toAdd.length} added, -${diff.toRemove.length} removed.`);
} else {
  console.log("Dataset.json: no changes needed.");
}

// ---------------------------------------------------------------------------
// Generate all.ttl and all.ttl.zip
// ---------------------------------------------------------------------------

if (!ALL_TTL_DIR) {
  process.exit(0);
}

const allTtlDirPath = path.resolve(workspace, ALL_TTL_DIR);

console.log("Generating all.ttl...");
const allTtlContent = generateAllTtlContent(sourceDirPath, currentNames);
writeAllTtlAndZip(allTtlDirPath, allTtlContent);
